### ISSUE TITLE
413 Client Error: Request Entity Too Large for url when uploading asset

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/assets.ubuntu.com#203]
maas-ui uploads tarballs to the asset server, but has started failing (last success 10th Jan, failing since)  with 

`413 Client Error: Request Entity Too Large for url`

When attempting to upload a 4.2Mb tarball which is then base64 encoded.

My $0.02: Since it's an asset server, it should allow larger uploads!

**Comment by goulinkh** [comment]
We are having trouble with continuous deployment where Jenkins isn't able to connect to one of the k8s clusters, so I had to deploy an update to assets manually where I missed increasing the size limit, it should be good to go now, sorry for the inconvenience!
