### ISSUE TITLE
MAAS UI uploads failing 413 - Request Entity Too Large

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/assets.ubuntu.com#231]
>   Failed due to error in `upload-assets` snap https://snapcraft.io/upload-assets

```
requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://assets.ubuntu.com/v1
Error: Process completed with exit code 1.
```

File size has not changed since the last time the build succeeded and remains at 3.2M
https://github.com/canonical/maas-ui/actions/runs/4596772848/jobs/8118655618

_Originally posted by @petermakowski in https://github.com/canonical/maas-ui/issues/4853#issuecomment-1505077262_

**Comment by VergilYotov** [comment]
I am getting the same issue using manager.assets.ubuntu.com and trying to upload a 1.6 MB file.

**Comment by petermakowski** [comment]
This is still unresolved and currently blocking MAAS releases.

In case this helps, here are the steps to reproduce this issue using the web UI: 
1. Create a 1MB testfile, using command `dd if=/dev/zero of=testfile bs=1M count=1`
2. Go to [manager.assets.ubuntu.com](https://assets.ubuntu.com/manager/create)
3. Submit the testfile
An error is thrown

**Comment by carkod** [comment]
I believe this project is now owned by systems, so maybe @samhotep @nottrobin can schedule some time to take a look?

**Comment by bartaz** [comment]
Based on dev-catchup discussion, this is blocking MAAS team from releasing beta version.

This also has been reported separately by people not being able to upload larger PDFs or things like that.

**Comment by nottrobin** [comment]
I'll look into it. I'm assuming nginx or maybe content-cache need to be configured with a higher limit. It probably means liaising with IS.

@sparkiegeek, am I right in thinking the last time this succeeded was April 3rd at 12:40 UTC, and then it failed at 15:31 UTC the same day? Is that then the window when we think this issue was introduced?

**Comment by nottrobin** [comment]
After some playing around, the size limit for uploading to the assets server now appears to be just over 786357 bytes, or about 0.75 MiB.

**Comment by sparkiegeek** [comment]
> I'll look into it. I'm assuming nginx or maybe content-cache need to be configured with a higher limit. It probably means liaising with IS.
> 
> @sparkiegeek, am I right in thinking the last time this succeeded was April 3rd at 12:40 UTC, and then it failed at 15:31 UTC the same day? Is that then the window when we think this issue was introduced?

That sounds right

**Comment by nottrobin** [comment]
After some playing around, the size limit for uploading to the assets server now appears to be just over 786357 bytes, or about 0.75 MiB.

**Comment by petermakowski** [comment]
@nottrobin is there any update on this, or do we have an estimated timeframe for a fix? This is of critical priority for us as it's preventing us from releasing the MAAS snap.

**Comment by nottrobin** [comment]
@petermakowski I've finally figured it out!

Currently you should now be able to submit large files to assets.ubuntu.com! Please go ahead and do this now as needed.

This will only last as long as nobody runs a release of assets.ubuntu.com, until these PRs are merged:

https://github.com/canonical/konf/pull/40
https://github.com/canonical/assets.ubuntu.com/pull/233

Once those are approved and merged this change should be permanent.
