### ISSUE TITLE
Enable pagination for the get_assets endpoint

### ISSUE THREAD

**Issue by jmuzina** [canonical/assets.ubuntu.com#242]
The [get_assets](https://github.com/canonical/assets.ubuntu.com/blob/98d338cc1268097ad0f86501c78e8f9f4d968378/webapp/views.py#L154) endpoint doesn't seem to support pagination. This can lead to very long wait times and unnecessary server load if a search query is sufficiently generic. 

It would be nice if this endpoint supported pagination (i.e.., accept `start` and `limit` parameters, or perhaps just a `page` parameter with a predefined number of results per page) to only fetch a subset of results matching a query, rather than the entire resultset.

Then the front-end could be updated to pull in pages of data rather than the entire resultset. Perhaps the [Vanilla Pagination pattern](https://vanillaframework.io/docs/patterns/pagination) would be of good use here.

**Comment by goulinkh** [comment]
Hey @jmuzina, I think this is a great idea for performance improvement on the manager UI.
In order to avoid making breaking changes I would suggest leaving the default option to query all assets, with the possibility to query paginated assets when the client provides the pagination query params.
